# Generated by Django 4.2.5 on 2023-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imageproj',
            field=models.ImageField(default='media/default.jpg', upload_to='proyectos/media/'),
            preserve_default=False,
        ),
    ]
