# Generated by Django 4.2.5 on 2023-10-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_imageproj'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imageproj',
            field=models.ImageField(null=True, upload_to='proyectos_imagenes/'),
        ),
    ]
